version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2_database
    ports:
      - "5432:5432"
    environment:
      H2_OPTIONS: '-ifNotExists'
    volumes:
      - h2_data:/opt/h2-data

volumes:
  h2_data:
    driver: local